### ISSUE TITLE
Pose Error, cant Import

### ISSUE THREAD

**Issue by HuxleyR77** [daz3d/DazToBlender#129]
For some reason the base poses don't work for me anymore, and the custom ones never worked for me. any solution? I am using blender 3.2 and the latest DazBridge Addon
![POSE ERROR](https://user-images.githubusercontent.com/85714805/173661286-34888f65-995e-49a6-90b5-47349851bf02.jpg)

**Comment by danielbui78** [comment]
I've confirmed that the "Import Pose" button works for applying "Base Pose Walking A.duf" onto a Genesis 8 Female figure, using Daz 4.20, Blender 3.2, and latest Daz To Blender Bridge on Windows 10.  Based on your traceback, it looks like the issue is related to not being able to correctly select the Daz Figure in the scene.  Are you trying to use the "Import Pose" button without having a fresh Daz character loaded into the scene?

**Comment by HuxleyR77** [comment]
reinstall all programs and addons, apparently it was a python security problem, a window came up and I applied ignore the problem. now it works. but only the base poses. my created poses don't work, no way.

**Comment by HuxleyR77** [comment]
ok thanks I will be on the lookout for the corrections.
