### ISSUE TITLE
daz to blender vridge bug

### ISSUE THREAD

**Issue by kissmecomix** [daz3d/DazToBlender#137]
when i  try to port a daz character into blender via, bridge i get folder er only no mesh 
![image](https://user-images.githubusercontent.com/86208388/179631262-087d067f-51b5-4756-986d-e431bbf86bdd.png)

i also have 3 scripts for blender on the DAZ side Daz to Blender. Daz to Blender: Genitals, Daz to blender:morph exporter

very frustrating

**Comment by danielbui78** [comment]
There have a number of changes to how to install and how to use the Blender bridge since the June update.  Please make sure you are following the new directions for how to fully install and use the Bridge:
Forums: https://www.daz3d.com/forums/discussion/572806/official-daztoblender-bridge-2022-what-s-new-and-how-to-use-it/p1

If you are still having problems, try manually updating to the latest github release using these instructions:
https://www.youtube.com/watch?v=LDDPfygZfgs

**Comment by danielbui78** [comment]
Closing this issue, since #141 appears to be the continuation of the same problem.
