### ISSUE TITLE
Elbow bending does not work correctly in Blender 3.3.x

### ISSUE THREAD

**Issue by chlbrn** [daz3d/DazToBlender#154]
![elbowbending](https://user-images.githubusercontent.com/10245612/203564936-faea5f61-4e46-414e-84c6-126b3f9e1eed.png)
Here is a comparison between genesis 8 female figure in Blender 3.2 and 3.3.
As you can see the elbow doesn't bend correctly.
It is the same file just opened with different Blender version. 
It works fine in Blender 3.2 but I think bending related JCMs don't work as intended in Blender 3.3.

Here is the complete description

System Info:
Operating System: Windows 11 pro 22H2
Graphics card: Geforce RTX 2080ti   522.30

Blender Version
3.3.0 and 3.3.1

Daz and Bridge version
Daz 4.20.0.17
Bridge 2022.2 revision 18.42

Exact steps to reproduce the error
1. Open Daz studio and load genesis 8 basic female figure
2. Use send to menu to open bridge
3. Leave everything default only add JCMs to Morphs and check 'Export Morphs' option
4. Accept all option and wait for exporting
5. Open Blender 3.3.x and show side tab and in Daz to Blender tab hit Import New Genesis Figure button.
6. Save file and close Blender
7. Open Blender and load the file just saved
8. In pose mode, rotate forearm or use IK to make elbow bend, the incorrect result will appear.

I tried installing the bridge from Daz install manager and manual installation from github, both are the same on my end.
In Blender 3.3, few times it worked but most of the time it just didn't work for me.
However I tied to open that file in Blender 3.2, it worked again. So it has to be an error with Blender 3.3
Any help would be appreciated

**Comment by chlbrn** [comment]
@danielbui78 Hi Daniel, are you still developing the bridge? Could you please take a look at this problem?
Thanks in advance

**Comment by danielbui78** [comment]
Yes, I'm looking into.  Sorry for delays, thanks for your patience.

**Comment by danielbui78** [comment]
I've been trying to get DazToBlender to break and cause the errors that you have described, but I have not yet been able to do so.  I am working on updates including a troubleshooting script but these won't be completed until mid-January.  Until then, please double-check the "Auto Run Python Scripts" setting and make sure it is **OFF** and make sure you are explicitly allowing python scripts to run every time you import instead of permanently turning it on, and make sure you have the JCM morphs present and that they are active and being applied and that the JCM is correctly linked as a driver type "Scripted Expression".

![auto run python scripts](https://user-images.githubusercontent.com/11391924/207659564-b64b88f8-1769-4f9b-b712-626a6044449e.png)

![verify JCMs are present and active](https://user-images.githubusercontent.com/11391924/207659628-2dbe6fd9-12e1-42c8-8430-ac6c534a8ea8.png)

![driver type scripted expression](https://user-images.githubusercontent.com/11391924/207659657-db6eab93-d561-4334-8e62-fbeb217ef2b0.png)

**Comment by chlbrn** [comment]
> 

Thanks for your detailed reply. It seems weird to me on my PC. Most of the JCMs are totally working fine for both Blender 3.3 and 3.2 but only elbow and knee bending JCMs don't work very well. I will keep testing and try to find why.

**Comment by chlbrn** [comment]
@danielbui78  Hi Daniel,
After some trial and error, I found some strange behavior on my end.
In Blender 3.3, shape key: pJCMForeArm_75_L/R and pJCMForeArm_135_L/R doesn't update along with elbow bending.
However, if I double click those shape key value in Object Data Properties tab, it works again.
The problem is that when I close Blender and re-open Blender, those shape key drivers don't update again.
Could you check this?

**Comment by chlbrn** [comment]
I tried Blender 3.4.1 yesterday. And it gave me the same result as 3.3.x
I found error inside driver editor, here is the error when I just opened file:
![DriverError1](https://user-images.githubusercontent.com/10245612/209634619-c5e3f1b6-f6f8-45ff-b649-33c3b025b3ee.png)

and after I updated dependencies it works again:
![DriverError2](https://user-images.githubusercontent.com/10245612/209634701-a5b95aa3-fb1f-42e5-9814-cb66f847680b.png)

It shows slow python expression warning but it works as intended. I think by default Blender doesn't update all driver dependencies but I don't know why. Most of the drivers work fine without warning or error. But there are at least 8 drivers are affected(2 for left arm, 2 for right arm, 2 for left leg and 2 for right leg). 
Can you verify this? @danielbui78

**Comment by chlbrn** [comment]
Hi Daniel, 
I think I found the cause. After disabling a 3rd party addon called 3D Hair Brush, the shape key drivers work as intended.
Probably there exist some compatibility issues between DTB and 3D Hair Brush. But after all, I am able to make DTB work again.
