### ISSUE TITLE
2.3.0.1 Blender plugin error: "Appropriate FBX does not exist"

### ISSUE THREAD

**Issue by Seraphiel0** [daz3d/DazToBlender#25]
1. Replaced DS scripts with items from package.  Behavior is updated; morph selection panel appears.  It's unclear if it will automatically include those with changed values or if I need to locate and select all of them individually.
2. Replaced Blender plugin scripts.  Validated correct version shows in preferences panel.  Tool panel is updated with new buttons.
3. In DS: Attempted to export existing 8.1 figure, completed export script inputs, waited for process to complete.
4. In Blender plugin: "Import new Genesis figure" produces error: "Appropriate FBX does not exist!"
5. Loaded new, empty DS scene, new 8.1 figure, repeated process and got same error from Blender plugin.

**Comment by samjay3d** [comment]
Hi there sorry you have issues importing with this update.

Thanks for testing it btw!

First off with the new morph dialog. I will add some more concrete explanation soon but, he the gist of it.
1. Select through the options on the left and it will show the morphs in that folder. 
2. Once you do you should see the morphs you can export out in the second column. 
3. Select the ones you want to export. (Left click one, Hold Ctrl if you wish to select multiple, Hold shift to select a multiple selection, or left click and drag for the ones you want)
4. Once you have your selection click add to export.
5. And press accept.

It will always open the dialog with your last used selection, if you want to save a selection press save preset and name as you like. Then you can press the dropdown to choose which preset you would like.

Anyway, let's see where the issue is coming from. 
Can you please check this location if the fbx is actually missing?

C:\Users\"YOUR USERNAME"\Documents\DAZ 3D\Bridges\Daz To Blender\Exports\FIG\FIG0

In that folder will be all the files needed for export. Is the fbx there?

**Comment by Seraphiel0** [comment]
No worries, just one of the perils of beta testing.

I should open an enhancement request for the morph dialog.  I like having the option, but something on the previous dialog like 'transfer all active/changed morphs' and just skip that part.  I'll log that separately later.

There is an fbx in that path along with other files I would see in the Documents\DTB path in previous builds.  It looks like the export is working.
![image](https://user-images.githubusercontent.com/48770299/112760484-fc4cc000-8fab-11eb-8056-cda6d40b0e00.png)


...and I tried it again just now after several attempts last night closing/re-opening both apps, and for some reason this is working now.  Got some other things going on, will log those separately.  Sorry for the false alarm, thanks for helping and making such a handy tool. :)
