### ISSUE TITLE
Shape keys animations not imported properly. FaceCap face capture + FaceMojo

### ISSUE THREAD

**Issue by YeMyintThu-Garfield** [daz3d/DazToBlender#49]
Here are DUF and BLEND files
https://drive.google.com/drive/folders/1E8xKA1qHkJLnvUQuZyIwSLq4uyAsMQra?usp=sharing

**Comment by samjay3d** [comment]
Is this the product you are talking about? 

https://www.daz3d.com/face-mojo--facial-mocap-retargeting-for-genesis-8-males

**Comment by YeMyintThu-Garfield** [comment]
Yes it is. I now get the problem. I cannot export the FACS and animations at the same time. Plus, even if I export as only animations, one FACS gets left behind, which is called eyeLookRightOut.
I'm not sure it's because of the bridge or the product. I'm sorry if I have caused any inconveniences.

Ye Myint Thu

________________________________

**Comment by samjay3d** [comment]
Unfortunately, this type of morph is not supported at this moment. It controls the bone directly. In Daz when you have a morph controlling a bone you can still animate it but, if you do that in blender you can not. Sorry for the inconvenience this may cause I will still look into a workaround but, it won't work for the time being. Some of those morphs do work just not all of them unfortunately because of that issue.

**Comment by YeMyintThu-Garfield** [comment]
Okay. Thank you. It's not a big problem. I was just experimenting.

Ye Myint Thu

________________________________
